version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - POSTGRES_DB=bmi
      - POSTGRES_USER=bmiuser
      - POSTGRES_PASSWORD=bmipass

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bmi
      POSTGRES_USER: bmiuser
      POSTGRES_PASSWORD: bmipass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d

volumes:
  db_data:
